version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  cypress:
    image: cypress/included:12.17.4
    container_name: cypress
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: /e2e
    volumes:
      - ./:/e2e

  newman:
    image: postman/newman:latest
    container_name: newman
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: /collection
    volumes:
      - ./:/collection

  k6:
    image: grafana/k6
    container_name: k6
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: /scripts
    volumes:
      - ./:/scripts

volumes:
  jenkins_home:
